CommunityApp/CommunityApp/Controllers/EventController.cs
using CommunityApp.Business.ServiceContracts;
using CommunityApp.Entity;
using CommunityApp.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CommunityApp.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventService _eventService;

        public EventController(IEventService eventService)
        {
            _eventService = eventService;
        }

        // GET: Event
        public ActionResult Index()
        {
            return View(_eventService.GetAllEvents());
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(EventViewModel eventModel)
        {
            try
            {
                EventInfo newEvent = new EventInfo();

                if (ModelState.IsValid)
                {
                    newEvent.Name = eventModel.Name;
                    newEvent.Description = eventModel.Description;
                    newEvent.Capacity = eventModel.Capacity;
                    newEvent.Location = eventModel.Location;
                    newEvent.StartDate = eventModel.StartDate;
                    newEvent.EndDate = eventModel.EndDate;
                    newEvent.CreatedBy = User.Identity.GetUserName();
                    newEvent.CreatedDate = DateTime.Now;
                    newEvent.IsActive = true;
                    newEvent.UpdatedBy = User.Identity.GetUserName();
                    newEvent.UpdatedDate = newEvent.CreatedDate;

                    if (_eventService.CreateEvent(newEvent))
                    {
                        return RedirectToActionPermanent("Index", "Home");
                    }
                }

            }
            catch (Exception ex)
            {
                Logger.Log.GetLogger().Error(ex);
            }

            return View();
        }
    }
}

CommunityApp/CommunityApp/Views/Shared/_DarkBodyView.cshtml
<div class="dark-body">
    <div class="container">
        <h2 class="recentPosts text-center">Recent Blog Posts</h2>
        <div class="row">
            <div class="col-md-3">
                <div class="blogSummary">
                    <div class="blogImg"><img src="~/images/blog01.png"></div>
                    <h3><a href="#">IoT Hub throttling and you</a></h3>
                    <p class="blogMeta">Wednesday, April 20, 2016</p>
                    <p>One of the questions I field the most often from folks has to do with how IoT Hub throttles certain operations.</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="blogSummary">
                    <div class="blogImg"><img src="~/images/blog02.png"></div>
                    <h3><a href="#">Azure Media Services announces collaboration with THEOplayer</a></h3>
                    <p class="blogMeta">Wednesday, April 20, 2016</p>
                    <p>With THEOplayer, video publishers can use a single video player to reach..</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="blogSummary">
                    <div class="blogImg"><img src="~/images/blog03.png"></div>
                    <h3><a href="#">JSON functionalities in Azure SQL Database (public preview)</a></h3>
                    <p class="blogMeta">Tuesday, April 19, 2016</p>
                    <p>We are happy to announce public preview of new JSON functionalities in Azure SQL Database.</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="blogSummary">
                    <div class="blogImg"><img src="~/images/blog04.png"></div>
                    <h3><a href="#">Optimizing document search using Machine Learning and Text Analytics</a></h3>
                    <p class="blogMeta">Tuesday, April 19, 2016</p>
                    <p>Azure ML Text Analytics can both optimize the content in Azure Search and improve the search experience by not only reducing the index size</p>
                </div>
            </div>
        </div>
        <div class="text-center">
            <a href="#" class="btn btn-lg btn-blue">View all posts</a>
        </div>
    </div>
</div>

CommunityApp/CommunityApp/Views/Shared/_FooterView.cshtml
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-4">
                        <h3>Learning resources</h3>
                        <ul>
                            <li><a href="#">Microsoft Virtual Academy</a></li>
                            <li><a href="#">Channel 9</a></li>
                            <li><a href="#">MSDN Magazine</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>Community</h3>
                        <ul>
                            <li><a href="#">Forums</a></li>
                            <li><a href="#">Blogs</a></li>
                            <li><a href="#">Codeplex</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>Programs</h3>
                        <ul>
                            <li><a href="#">BizSpark (for startups)</a></li>
                            <li><a href="#">DreamSpark</a></li>
                            <li><a href="#">Imagine Cup</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Support</h3>
                        <ul>
                            <li><a href="#">Self support</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <h3>Follow Us</h3>
                        <ul class="social">
                            <li>
                                <a href="#"><i class="fa fa-facebook-square"></i></a>
                                <a href="#"><i class="fa fa-twitter-square"></i></a>
                                <a href="#"><i class="fa fa-google-plus-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footerBtm">
            <ul>
                <li><a href="#">Newsletter</a></li>
                <li><a href="#">Privacy &amp; cookies</a></li>
                <li><a href="#">Terms of use</a></li>
                <li><a href="#">Trademarks</a></li>
            </ul>

        </div>
    </div>
</div>

CommunityApp/CommunityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WinServer Community Nepal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/slider")
    
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="header">
        @Html.Partial("_Navigation")   
    </div>
    <div>
        @RenderBody()
    </div>
    @Html.Partial("_FooterView")    
        
</body>
</html>

CommunityApp/CommunityApp/Views/Shared/_LightBodyView.cshtml
<div class="light-body">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="~/images/video.png">
            </div>
            <div class="col-md-6">
                <h2>Get Started</h2>
                <p>Some details about the event goes here. Some details about the event goes here. Some details about the event goes here. Some details about the event goes here.</p>
                <p><strong>Participate in this event, this April and learn more about Microsoft.</strong></p>
                <p><a href="#" class="btn btn-lg btn-blue">Join Event</a></p>
            </div>
        </div>
    </div>
</div>

CommunityApp/CommunityApp/Views/Shared/_MessageView.cshtml
<div class="message">
    <div class="container">
        <p><a href="#">Missed our last event? Well, you can know everyting about it here <i class="fa fa-angle-right"></i></a></p>
    </div>
</div>

CommunityApp/CommunityApp/Views/Shared/_Navigation.cshtml
<div class="container">
    <div class="topLine clearfix">
        <div class="brand-logo pull-left"><img src="~/images/logo.png"></div>
        <div class="visible-xs-block pull-right">
            <a class="" data-toggle="collapse" href="#mainMenu" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-bars"></i></a>
        </div>
        <div class="search-header pull-right">
            <div class="input-group">
                <input type="text" class="form-control input-sm" placeholder="Search..">
                <span class="input-group-btn">
                    <button class="btn btn-sm"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>
        <div class="pull-right">

        </div>
    </div>
    <div class="btmLine clearfix">
        <ul id="mainMenu" class="nav navbar-nav collapse navbar-collapse">
            <li class="active">
                @Html.ActionLink("Home", "Index", "Home")
            </li>
            <li>
                @Html.ActionLink("About Us", "About", "Home")
            </li>
            <li>
                @Html.ActionLink("Forum", "Index", "Forum")
            </li>
            <li>
                @Html.ActionLink("Events", "Index", "Event")
            </li>
            <li>
                @Html.ActionLink("Blog", "Index", "Blog")
            </li>
            <li>
                @Html.ActionLink("Contact", "Contact", "Home")
            </li>
            <li></li>
        </ul>
        @Html.Partial("_LoginPartial")

    </div>

    <div class="pull-right header-right">

        <span class="user-links">

        </span>
    </div>
</div>

CommunityApp/CommunityApp/Views/Shared/_SliderView.cshtml
<div class="sliderContainer">
    <div class="slider">
        <ul class="bxslider">
            <li>
                <img src="~/images/slider01.png">
                <div class="sliderDescription">
                    <h2>Microsoft Lumia 650 finally lands at Cricket</h2>
                    <p>This will be the only US carrier that will sell the Lumia 650, it turns out.</p>
                    <p><a href="#" class="btn btn-lg btn-blue">Join Now <i class="fa fa-angle-right"></i></a></p>
                </div>
                <div class="sliderCover"></div>
            </li>
            <li>
                <img src="~/images/slider02.png">
                <div class="sliderDescription">
                    <h2>Microsoft sold 2.3 million Lumia devices</h2>
                    <p>Microsoft has released its Q3 fiscal 2016 earnings report.</p>
                    <p><a href="#" class="btn btn-lg btn-blue">Join Now <i class="fa fa-angle-right"></i></a></p>
                </div>
                <div class="sliderCover"></div>
            </li>
        </ul>
    </div>
</div>